import Head from "next/head";
import Navbar from "../components/Navbar";
import Link from "next/link";
import Image from "next/image";
import Hero from "../components/Hero";



// Notification.requestPermission(function() {
//   if (Notification.permission === 'granted') {
//   // user approved.
//   // use of new Notification(...) syntax will now be successful
//   } else if (Notification.permission === 'denied') {
//   // user denied.
//   } else { // Notification.permission === 'default'
//   // user didn’t make a decision.
//   // You can’t send notifications until they grant permission.
//   }
//   new Notification('Hello', { body: 'Second Notification', icon: 'http://127.0.0.1:5500/assests/logo.svg' });
  
//  });

export default function Home() {
  function openMenu() {
    var element = document.getElementById("menu");
    element.classList.toggle("open-menu");
  }
  
  return (
    <>
    
      <Head>
        <title>IGNOU BCA Club</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/images/favicon.png" type="image/x-icon" />
        
      </Head>
      <Navbar />
      {/* <Hero /> */}
      <div className="hero">
        <div className="hero-content">
          <h3>Everything for IGNOU BCA Students</h3>
          <h1>
            Welcome to
            <br />
            ignou BCA Club
          </h1>
          <p>
            This website is created to help IGNOU BCA students by providing all study material and other resources at one place to them.
          </p>

          <button className="cta" onClick={openMenu}>Explore Us</button>
        </div>
      </div>
      <section className="index">
        <h2>Available Semesters</h2>
        <ul>
          <Link href="/semester2/"><a>
            <Image src='/images/2nd-semester-bag.svg' width='150px' height='200px'/></a></Link>
        </ul>
      </section>
    </>
  );
}
