import Head from "next/head";
import Navbar from "../components/Navbar";
import Link from "next/link";
import Image from "next/image";


export default function Home() {
  function openMenu() {
    var element = document.getElementById("menu");
    element.classList.toggle("open-menu");
  }
  
  return (
    <>
    
      <Head>
        <title>IGNOU BCA Club</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/images/favicon.png" type="image/x-icon" />
        
      </Head>
      <Navbar />
      {/* <Hero /> */}
      <div className="hero">
        <div className="hero-content">
          <h3>Everything for IGNOU BCA Students</h3>
          <h1>
            Welcome to
            <br />
            ignou BCA Club
          </h1>
          <p>
            This website is created to help IGNOU BCA students by providing all study material and other resources at one place to them.
          </p>

          <button className="cta" onClick={openMenu}>Explore Us</button>
        </div>
      </div>
      <section className="index">
        <h2>Available Semesters</h2>
        <ul>
          <Link href="/semester2/"><a>
            <Image src='/images/2nd-semester-bag.svg' width='150px' height='200px' alt="semester 2 bag"/></a></Link>
        </ul>
      </section>
    </>
  );
}
