import Head from "next/head";
import Navbar from "../components/Navbar";
import Link from "next/link";
import Image from "next/image";
import Hero from "../components/Hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>IGNOU BCA Club</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.svg" />
      </Head>
      <Navbar />
      {/* <Hero /> */}
      <section className="hero">
        <div className="hero-content">
          <h3>Everything for IGNOU BCA Students</h3>
          <h1>
            Welcome to
            <br />
            ignou BCA Club
          </h1>
          <ul>
            <li>Ebooks</li>
            <li>Syllabus</li>
            <li>Assignments</li>
            <li>Previous Year Question Paper</li>
            <li>And many more ....</li>
          </ul>

          <button className="cta">Explore Us</button>
        </div>
      </section>
    </>
  );
}
